# Generated by Django 4.1 on 2022-09-19 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_comment_is_active_comment_recomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='recomment',
            new_name='recommend',
        ),
    ]
